recipe: default.v1

assistant_id: 20250325-152540-immediate-convolution

language: "ko"
pipeline:
  - name: SpacyNLP
    model: "ko_core_news_sm"  # 사용하려는 모델 이름
    case_sensitive: False
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexEntityExtractor
  - name: CRFEntityExtractor
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
